"""CIE Platform — R script cache.

Caches LLM-generated R scripts so that commonly-performed analyses do not
re-spend LLM tokens on every run (user requirement: "keep common analyses in
cache to avoid wasting AI tokens"). Mirrors the semantic-cache philosophy of
:class:`cie.cache.store.CacheStore` but is keyed on the *analysis shape*
(method + variable roles + column signature) rather than the raw prompt, so
structurally-identical analyses reuse the same script regardless of wording.

Cache identity (CA-005 parity) includes the LLM provider and model so a model
change never serves a script generated by a different model.
"""

from __future__ import annotations

import hashlib
import json
import threading
from datetime import datetime, timezone
from pathlib import Path

_CACHE_VERSION = "1.0"


class RScriptCache:
    """File-backed cache of generated R scripts.

    Args:
        cache_dir: Directory holding ``r_script_cache.json``. Defaults to this
            module's directory.
    """

    def __init__(self, cache_dir: Path | str | None = None) -> None:
        base = Path(cache_dir) if cache_dir is not None else Path(__file__).parent
        base.mkdir(parents=True, exist_ok=True)
        self._path = base / "r_script_cache.json"
        self._lock = threading.Lock()

    @staticmethod
    def make_signature(
        method_id: str,
        intent_object: dict,
        column_signature: str,
    ) -> str:
        """Build a stable signature for the analysis shape.

        Uses the method, the variable roles (outcome/predictor var_n + role),
        distribution assumption, paired flag, and a caller-provided column
        signature. Wording of the original prompt is intentionally excluded.
        """
        shape = {
            "method_id": method_id,
            "outcome_variables": intent_object.get("outcome_variables", []),
            "predictor_variables": intent_object.get("predictor_variables", []),
            "outcome_type": intent_object.get("outcome_type"),
            "paired": intent_object.get("paired"),
            "distribution_assumptions": intent_object.get("distribution_assumptions"),
            "columns": column_signature,
        }
        raw = json.dumps(shape, sort_keys=True, ensure_ascii=False)
        return hashlib.sha256(raw.encode("utf-8")).hexdigest()

    def _entry_hash(self, signature: str, provider: str, model: str) -> str:
        raw = "\n".join([signature, provider, model])
        return hashlib.sha256(raw.encode("utf-8")).hexdigest()

    def get(self, signature: str, provider: str, model: str) -> str | None:
        """Return a cached R script for the signature, or None on miss."""
        with self._lock:
            data = self._load()
            entry = data["entries"].get(self._entry_hash(signature, provider, model))
            if entry is None:
                return None
            entry["use_count"] = entry.get("use_count", 0) + 1
            entry["last_used_at"] = datetime.now(timezone.utc).isoformat()
            self._save(data)
            return entry.get("r_script")

    def put(
        self,
        signature: str,
        r_script: str,
        provider: str,
        model: str,
        method_id: str = "",
    ) -> None:
        """Store a generated R script under the signature."""
        now = datetime.now(timezone.utc).isoformat()
        with self._lock:
            data = self._load()
            data["entries"][self._entry_hash(signature, provider, model)] = {
                "signature": signature,
                "method_id": method_id,
                "r_script": r_script,
                "llm_provider": provider,
                "llm_model": model,
                "created_at": now,
                "last_used_at": now,
                "use_count": 0,
            }
            self._save(data)

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _load(self) -> dict:
        if not self._path.exists():
            return {"version": _CACHE_VERSION, "entries": {}}
        try:
            data = json.loads(self._path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return {"version": _CACHE_VERSION, "entries": {}}
        if not isinstance(data, dict) or not isinstance(data.get("entries"), dict):
            return {"version": _CACHE_VERSION, "entries": {}}
        return data

    def _save(self, data: dict) -> None:
        self._path.write_text(
            json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8"
        )
